version: '3.8'
services:
  factorio:
    build: .
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - factorio_data:/factorio
    environment:
      - LD_PRELOAD=/usr/local/lib/mimalloc-1.7/libmimalloc.so
      - HUGETLB_MORECORE=thp
      - MIMALLOC_LARGE_OS_PAGES=1
    sysctls:
      - net.core.rmem_max=16777216
      - net.core.wmem_max=16777216
      - net.ipv4.tcp_rmem=4096 87380 16777216
      - net.ipv4.tcp_wmem=4096 65536 16777216

volumes:
  factorio_data:
